import type { Metadata } from 'next';
import './globals.css'; // ตรวจสอบให้แน่ใจว่า import ไฟล์ css ถูกต้อง

export const metadata: Metadata = {
  title: 'ROPA Management System',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="th">
      <body>{children}</body>
    </html>
  );
}